### PR TITLE
Drop logtash config resource

### PR DESCRIPTION
**Pull request by eherot**
Also was intended for @EdHurtig to review if he's available.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@eherot this all looks legit, though I’m trusting that it maintains the current functionality, based on the lack of changes to actual filters/regexs/whatever they’re called.

**Comment by eherot** [comment]
That is the intention, yes, although it's very breaking on account of moving basically all of the attributes around.

**Comment by jeffbyrnes** [comment]
Yeah, no doubt of that in my mind, but that’s why we have breaking version numbers ;)

**Comment by EdHurtig** [comment]
@eherot I think this should be pretty solid... Will give it a look later today

**Comment by jeffbyrnes** [comment]
@EdHurtig manage to give this another look? Would love to keep this moving along.

**Comment by EdHurtig** [comment]
@evertrue/devops Just looked this over, looks good... only concern lies with the et_elk cookbook default attributes `default['et_elk']['server']['config']['input']['lumberjack']...` and `default['et_elk']['server']['config']['input']['log4j']...` which will enable those inputs by default without an easy way to disable them... but that is a bit of an over engineering thing that we can address later.  

:+1:

**Comment by jeffbyrnes** [comment]
@eherot seems like this can move forward :tada:

**Pull request merged**
